version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
    networks:
      - derdevam

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - derdevam


  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - derdevam
    depends_on:
      - api

  api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    networks:
      - derdevam

networks:
  derdevam:

volumes:
  postgres-data: